name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker hubm
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set tag number
        id: set_tag
        run: echo "::set-output name=tag_number::0.$((GITHUB_RUN_NUMBER - 1))"

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/react-melivecode:${{ steps.set_tag.outputs.tag_number }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/react-melivecode:${{ steps.set_tag.outputs.tag_number }}